### PR TITLE
Make ${PostgreSQL_INCLUDE_DIRS} private to avoid unintentionally accessing PostgreSQL's headers

### LINKED ISSUE #52: Failed to cooperate with vcpkg in CMake
I have a `CMakeLists.txt` like this:

```
cmake_minimum_required(VERSION 3.21.4)

set(CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

# init dependencies
include(FetchContent)

# init vcpkg
FetchContent_Declare(
    vcpkg
    GIT_REPOSITORY  https://github.com/microsoft/vcpkg.git
    GIT_TAG         5bdb9d60123df20c247a1654e6a1def51d6c5140
    GIT_PROGRESS    TRUE
)
FetchContent_MakeAvailable(vcpkg)
execute_process(
    COMMAND sh ./bootstrap-vcpkg.sh --disableMetrics
    WORKING_DIRECTORY ${vcpkg_SOURCE_DIR}
    RESULTS_VARIABLE vcpkg_BUILD_RESULT
    COMMAND_ERROR_IS_FATAL ANY
)
set(CMAKE_TOOLCHAIN_FILE ${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")

project(xxx CXX)

# dep: taoPQ
execute_process(
    COMMAND ./vcpkg install libpq --clean-after-build
    WORKING_DIRECTORY ${vcpkg_SOURCE_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
find_package(PostgreSQL REQUIRED)

FetchContent_Declare(
   taopq
   GIT_REPOSITORY   https://github.com/taocpp/taopq
   GIT_TAG          8d9285f76726e312282ac2c1de70b3338b2c701d
   GIT_PROGRESS     TRUE
)
FetchContent_MakeAvailable(taopq)

...
```

But it failed with:

```
[cmake] -- Configuring done
[cmake] CMake Error in build/_deps/taopq-src/CMakeLists.txt:
[cmake]   Target "taopq" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include"
[cmake] 
[cmake]   which is prefixed in the build directory.
[cmake] 
[cmake] 
[cmake] CMake Error in build/_deps/taopq-src/CMakeLists.txt:
[cmake]   Target "taopq" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include"
[cmake] 
[cmake]   which is prefixed in the build directory.Target "taopq"
[cmake]   INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include"
[cmake] 
[cmake]   which is prefixed in the source directory.
[cmake] 
[cmake] 
[cmake] CMake Error in build/_deps/taopq-src/CMakeLists.txt:
[cmake]   Target "taopq" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include/postgresql/server"
[cmake] 
[cmake]   which is prefixed in the build directory.
[cmake] 
[cmake] 
[cmake] CMake Error in build/_deps/taopq-src/CMakeLists.txt:
[cmake]   Target "taopq" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include/postgresql/server"
[cmake] 
[cmake]   which is prefixed in the build directory.Target "taopq"
[cmake]   INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/home/iyang/xxx/build/_deps/vcpkg-src/installed/x64-linux/include/postgresql/server"
[cmake] 
[cmake]   which is prefixed in the source directory.
[cmake] 
[cmake] 
[cmake] -- Generating done
```

After I applied the following patch, CMake can be successfully configured.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 308c235..df1fc1a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -92,8 +92,8 @@ target_include_directories(taopq
   PUBLIC
     $<INSTALL_INTERFACE:include>
     $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
-    ${PostgreSQL_INCLUDE_DIRS}
   PRIVATE
+    ${PostgreSQL_INCLUDE_DIRS}
     ${CMAKE_CURRENT_SOURCE_DIR}/src
 )
```

So I think maybe the change can directly happen on the code to avoid this patch ?

BTW, `taoPQ` is a very wonderful thing, THANKS for your libraries!

### PR DESCRIPTION
**Pull request by iyanging**
fixes #52

### CODE REVIEW

**Comment by d-frey** [comment]
I probably don't understand how CMake works. Our headers include `libpq-fe.h`, so the dependency towards libpq requires their headers to be visible when our headers are used. I thought that this means that libpq's headers are a public requirement. This is also supported by the `src/test/pq/CMakeLists.txt` change you added, as our binaries should depend on taoPQ and that should automatically add the requirement for libpq. But now you added it manually, which should not be necessary IMHO. I'm confused. @uilianries Can you explain this to me?

**Comment by iyanging** [comment]
The reason why I make `libpq` visible to tests is that tests directly use it through `libpq-fe.h`. But I am also confused why CI cannot compile them successfully when I can compile them in my PC.

**Comment by uilianries** [comment]
>  so the dependency towards libpq requires their headers to be visible when our headers are used

If they need PostgreSQL so yes, it should to be public. If a public header includes a pq header, so it must be public. I though there was no link between pq headers and dependencies, was more internally only.

The test should not need to include pq directly, it should be exported by taopq. If it works or not in your environment, but fails on CI, we have an environment problem then.

Let me try to reproduce your case here.

**Comment by iyanging** [comment]
My Bad... It's `include/tao/pq/exception.hpp` who include `libpq-fe.h`.

You're right, libpq needs to be public.

**Comment by d-frey** [comment]
It's not just `exceptions.hpp`:

```
 frey@fiasko:~/work/git/taocpp/taopq:main  grep++ libpq-fe.h
./include/tao/pq/exception.hpp:#include <libpq-fe.h>
./include/tao/pq/result.hpp:#include <libpq-fe.h>
./include/tao/pq/notification.hpp:#include <libpq-fe.h>
./include/tao/pq/transaction.hpp:#include <libpq-fe.h>
./include/tao/pq/table_reader.hpp:#include <libpq-fe.h>
./include/tao/pq/oid.hpp:#include <libpq-fe.h>
./include/tao/pq/connection.hpp:#include <libpq-fe.h>
./src/lib/pq/result.cpp:#include <libpq-fe.h>
./src/lib/pq/table_writer.cpp:#include <libpq-fe.h>
./src/lib/pq/table_reader.cpp:#include <libpq-fe.h>
 frey@fiasko:~/work/git/taocpp/taopq:main  
```

**Comment by d-frey** [comment]
I'll close this one then, as this is clearly not the solution. Please re-open #52 if necessary and figure out what the actual problem is.

**Comment by uilianries** [comment]
Thank you for investigating and sharing.

**Pull request closed without merging**
